version: '3'

services:
  yolo-app:
    build: .
    container_name: yolo-detection
    restart: unless-stopped
    volumes:
      - ./static:/app/static
      - ./models:/app/models
    environment:
      - TZ=Asia/Jakarta
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 800M
        reservations:
          memory: 500M
    networks:
      - yolo-network

  nginx:
    image: nginx:alpine
    container_name: yolo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/static
    depends_on:
      - yolo-app
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge